# Write Kubernetes Deployment Script
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book_catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book_catalog
  template:
    metadata:
      labels:
        app: book_catalog
    spec:
      containers: 
      - name: book_catalog
        image: week08:1
        imagePullPolicy: Never
        env:
        - name: DATABASE_URL
          value: "postgresql://week08_hw97_user:QA2VyvFdKJx3TN6mYJRFXCVA2wcUIH3o@dpg-crfstfbqf0us73dbt1g0-a.oregon-postgres.render.com/week08_hw97"
---
apiVersion: v1
kind: Service
metadata:
  name: book_catalog
spec:
  selector:
    app: book_catalog
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000